### ISSUE TITLE
[FEATURE REQUEST] Pywal colorscheme

### ISSUE THREAD

**Issue by ThamognyaKodi** [ZenithDS/SpotiFetch#2]
Would it be possible to make a pywal color scheme that gets it color scheme from pywal.

**Comment by ZenithDS** [comment]
Hi! I don't have much experience with using pywal but after taking a brief look at how pywal operates, I think this feature could certainly be implemented. My experience with pywal is very limited but I can take a look as soon as I get time :)

**Comment by ZenithDS** [comment]
@ThamognyaKodi I've added experimental pywal support in the [pywal branch](https://github.com/ZenithDS/SpotiFetch/tree/pywal). 

It relies on pywal generating a  `colors.json` file in `$HOME/.cache/wal/` when a wallpaper is set.

The `--pywal` option can be used on any of the commands to use a colorscheme generated by pywal.  

Would you mind testing out the feature by installing from source on that branch?

**Comment by ThamognyaKodi** [comment]
@ZenithDS firstly thank you for considering to implement my suggestion

secondly, I have built it from source (pywal branch), and it works perfectly just as intended. The color scheme for spotifetch matches my background.

**Comment by ZenithDS** [comment]
@ThamognyaKodi Absolutely no problem! I had fun working on it and it gave me an excuse to try out pywal :)

The changes have been merged to the main branch and you can update it using pip. 

Also closing this since the changes have been finalized in 728bf90. Please keep me updated if any issues arise!!
